development:
  adapter: postgresql
  encoding: unicode
  database: omr_db_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: omr_db_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: omr_db_prod
  pool: 5